### PR TITLE
Updated: The string conversion and dumping for plants and controllers

### PR DESCRIPTION
**Pull request by dvdvideo1234**
Updated: The string conversion and dumping for plants and controllers

### CODE REVIEW

**Comment by dvdvideo1234** [comment]
Directories being used to include and concatenate all the needed folders at once:

```
local dir = require("directories")
      dir.addPath("myprograms",
                  "ZeroBraineProjects",
                  "CorporateProjects",
                  "ZeroBraineProjects/dvdlualib",
                  -- When not located in general directory search in projects
                  "ZeroBraineProjects/ExtractWireWiki").addBase("D:/LuaIDE").setBase()
```

**Comment by dvdvideo1234** [comment]
Hello, @pkulchenko is it any good ?

**Comment by dvdvideo1234** [comment]
Hello, @pkulchenko Is this going to be merged soon ?

**Comment by pkulchenko** [comment]
@dvdvideo1234, everything looks good to me, but I'd like to avoid `Merge branch 'patch-1'...` commits if possible. Can you rebase to eliminate them and force-push? I'll be happy to merge, as I've already reviewed the changes. If you want, you can just fixup/squash those merge commits into the previous one. Thank you and apologies for delay in reviewing/merging.

**Comment by dvdvideo1234** [comment]
Hello, @pkulchenko, I cannot remove https://github.com/pkulchenko/ZeroBraneEduPack/pull/39/commits/0521123dd7d78c855371a36137719c6792941582 as it is part of the git control merge system. I intended to fix that in https://github.com/pkulchenko/ZeroBraneEduPack/pull/39/commits/da46cbae6b1167543763cf6136563fde2541996e but it still stays conflicted, so I have to resolve it via the GitHub API.

Please merge ASAP.

**Comment by dvdvideo1234** [comment]
Closed, because my base repository is too much behind due to time being git isists to install older version of `complex.lua` which is incorrect. The cleanest way is to create a new PR and move the changes there. Tried to rebase 3 times with no luck. PRS is located here:

https://github.com/pkulchenko/ZeroBraneEduPack/pull/41

**Pull request closed without merging**
