### PR TITLE
Optimized and factorized game of like via common.lua

### PR DESCRIPTION
**Pull request by dvdvideo1234**

### CODE REVIEW

**Comment by pkulchenko** [comment]
@dvdvideo1234, can you remove 5a7b616 merge commit? You can just rebase your changes against the current master, which should remove that commit and will allow me to cleanly merge the changes. Thanks!

**Comment by dvdvideo1234** [comment]
But the merge will otherwise remove your change here: https://github.com/pkulchenko/ZeroBraneEduPack/commit/4fe2fb18c22a86288719bf341bc65db7c61cf97d

In it gonna be easier like it is now ?

**Comment by dvdvideo1234** [comment]
Done ;)

**Comment by pkulchenko** [comment]
Right; it will include the change if you rebase on top of it, like you did. Thanks!

**Pull request merged**
