### PR TITLE
Code factorization for Rules

### PR DESCRIPTION
**Pull request by dvdvideo1234**
Update: "getRuleBS" more minge-friendly as it  is seen outside the library
Update: Local hidden function are meant to be hidden in purpose ;)

### CODE REVIEW

**Comment by pkulchenko** [comment]
@dvdvideo1234, can you squash the too commits together?

**Comment by dvdvideo1234** [comment]
The merging gives that option ;) (  a.k.a. Squash and merge. That way all commits become one single commit ;). Currently cannot squash them because I don't have access to your repo )

Cheers !

**Comment by pkulchenko** [comment]
You don't need access to the repo or a new PR; you just squash them in your branch and do a force push.

**Comment by dvdvideo1234** [comment]
This should do it. They are now one commit in my repo

**Comment by pkulchenko** [comment]
Yes, although it left the second commit message, but it was better to keep the first one. I can fix it; what was the proper commit message for it?

**Comment by dvdvideo1234** [comment]
Code factorization for obtaining rule BS

**Comment by dvdvideo1234** [comment]
Amend and re-based.  Seems ok. Only needs your approval.

**Pull request closed without merging**
