### PR TITLE
Added: Coroutines example and some improvments

### PR DESCRIPTION
**Pull request by dvdvideo1234**
Add a coroutine example

### CODE REVIEW

**Comment by pkulchenko** [comment]
@dvdvideo1234, everything looks good. The only thing I'd update is the typos in the commit message `Added: More commntas explainig stuff`. Can you rebase it to update it to `Added: More comments explaining stuff` or something similar? Thanks!

**Comment by dvdvideo1234** [comment]
Yes, I will make the revision before the typo has been created the new head and update/add all the commit logs in one single revision. to make it cleaner. Since it's the third commit it cannot really be amended. And that way will be easier to be manipulated. Are you OK with this?

**Comment by pkulchenko** [comment]
@dvdvideo1234, you can definitely modify that commit. Just to `git rebase -i commit-hash~1` and them use `r` to update the commit message. You can then force push it to your branch and it will be all good.

**Comment by dvdvideo1234** [comment]
Combined the two logs about the comments change in one log and force-pushed. After cloning looks ok.
Tortoise Git I see made an automatic rebase :)

**Pull request merged**
