### PR TITLE
Use correct name for LÖVE framework

### PR DESCRIPTION
**Pull request by rm-code**
As with the [pull request](https://github.com/pkulchenko/ZeroBraneStudio/pull/433) in the ZeroBraneStudio repo, the name of the framework is LÖVE. 

It is often confused with love2d because that's the name of the project's webpage and also used as a hashtag on twitter, because (needless to say) #love is used quite often for a lot things unrelated to the framework.

### CODE REVIEW

**Comment by pkulchenko** [comment]
@rm-code, the changes look good, thank you, but I'd keep the folder name as is and just update the text and descriptions. We've had issues with Unicode file names in the past and I'd prefer to avoid using them in the repository.

**Comment by rm-code** [comment]
@pkulchenko Yikes! I didn't think about issues relating unicode file names - I should actually know better. I updated the pull request accordingly.

**Comment by rm-code** [comment]
@pkulchenko Force pushed another small update which removes the unicode char from the commit message (I just read your reply in the other pull request :wink:).

**Comment by pkulchenko** [comment]
Merged; thank you!

**Pull request merged**
