### PR TITLE
Fixed: Irregular undefined calls

### PR DESCRIPTION
**Pull request by dvdvideo1234**
Just small changes from the file merge

### CODE REVIEW

**Comment by dvdvideo1234** [comment]
I thought that this is pretty useful and it may be a must-have
image

**Comment by pkulchenko** [comment]
> I thought that this is pretty useful and it may be a must-have

Interesting; would it take a relative path as well (`"a/b/c"`)?

**Comment by dvdvideo1234** [comment]
Never tried it, but currently i have a project that contains multiple versions of itself in the same folder and I needed to include the complex library to be usable in all the versions separately ;)

**Comment by dvdvideo1234** [comment]
Renamed this to `common.addLibrary(sB, ...)` and updated it with vararg [in the last patch](https://github.com/pkulchenko/ZeroBraneEduPack/pull/38)

**Comment by dvdvideo1234** [comment]
API now adds directories including the Lua files directly
```lua
common.addLibrary("E:/Documents/Lua-Projs/ZeroBraineIDE/myprograms","a/b/c")
local t = require("test")
print(t.add(3,7)) -- Prints 10
```

**Pull request merged**
