### PR TITLE
Added: Education libraries

### PR DESCRIPTION
**Pull request by dvdvideo1234**
Add the ability to draw fractals. Based on my fractal example.

https://github.com/dvdvideo1234/ZeroBraineProjects/blob/master/DrawFractal/main.lua

### CODE REVIEW

**Comment by pkulchenko** [comment]
@dvdvideo1234, thank you for the patch; looks interesting!

I noticed couple of issues though: `clampValue` is not defined in fractal.lua and `Complex` is referenced, but not defined as well (missing `require'Complex'`? it's loaded in main.lua, but not in fractal.lua and it's better to return `Complex` as the result of `require`, rather than setting a global variable.)

**Comment by dvdvideo1234** [comment]
Fixed, Thank you

**Comment by dvdvideo1234** [comment]
I see this is located in "ZeroBraineIDE\myprograms" on Windows for  https://studio.zerobrane.com/

**Comment by dvdvideo1234** [comment]
The cellular automata database can be downloaded here:

http://www.conwaylife.com/patterns/all.zip

The idea is to have a simplified [Golly](http://golly.sourceforge.net/) like functionality

**Comment by pkulchenko** [comment]
> I see this is located in "ZeroBraineIDE\myprograms" on Windows for https://studio.zerobrane.com/

Yes, but it's only packaged this way when I build a distribution package. You don't need to include that path in the source code. In fact, I think `life.shapesPath("E:\\Documents\\Lua-Projs\\ZeroBraineIDE\\myprograms\\ZeroBraineProjects\\GameOfLife\\shapes")` in `conwaylife` example needs to be replaced with something relative, like `conwaylife-example/shapes` or `shapes` (depending on which folder is set as a project folder; you may need to check both).

I think it will make sense to include one or two small `.rle` files in the distribution, so the users can start on them right away and download more if they want to explore this further.

**Comment by dvdvideo1234** [comment]
Yep, that; correct ... But I am not sure how you want the shapes data to be structured ..

**Comment by pkulchenko** [comment]
Create `shapes` folder under `conwaylife-example`, put 3-5 most interesting .rle files there, and update the code to check for files in that folder. Then the users can dump the rest of the files there is they want and experiment with them.

**Comment by dvdvideo1234** [comment]
Well, it seems the path must be set relative to the current [project directory](https://user-images.githubusercontent.com/9112662/31985280-3641dec6-b96d-11e7-991b-fe4405ae637f.png), though if the user changes it, it might stop working.

**Comment by dvdvideo1234** [comment]
I have more examples like this, but gonna add them in separate PR when necessary.

**Comment by dvdvideo1234** [comment]
Are you gonna include this PR to next release of Zerobrane. If so it will be nice. I am gonna show a friend how to code lua ?

**Comment by pkulchenko** [comment]
Yes, plan to merge shortly.

**Comment by pkulchenko** [comment]
@dvdvideo1234, merged with a couple of small fixes; renamed one of the folders for consistency and updated the welcome page. Thank you!

**Pull request merged**
